import type { Metadata } from "next";
import 'bootstrap/dist/css/bootstrap.css';
import dynamic from "next/dynamic";
// import { Zen_Maru_Gothic } from 'next/font/google';
import '@/App.css'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter'; 
import TransitionProvider from "@/components/transition-context";
import AOSInitializer from "@/components/aos-initializer";
import Loader from "@/components/loader";
// import NavBar from "./_components/navBar";

// const DynamicBootstrap = dynamic(
// 	() => require('bootstrap/dist/js/bootstrap.min.js'),
// 	{ ssr: false }
// );

// const zen_maru_gothic = Zen_Maru_Gothic({
// 	weight: '400',
// 	subsets: ['latin']
// });

export const metadata: Metadata = {
	title: "Pokedex",
	description: "Pokedex App Generated by create next app",
};



type RootLayoutProps = {
	children: React.ReactNode
}

export default async function RootLayout(props: RootLayoutProps) {

	// prefetch data at build time, if we don't do this, sorting pokemons through weight/height... will cause routing unresponsive for a while (select --> nothing happens --> a while later --> url changes --> suspense fallback shows)
	// const responses = await Promise.all([...Array(1000).keys()].map(num => fetch(`https://pokeapi.co/api/v2/pokemon/${num + 1}`, {cache: 'force-cache'})));


	return (
		<html lang="en">
			{/* <body className={zen_maru_gothic.className}> */} 
			<body>
				{/* {props.search} */}
				<AOSInitializer/>
				<TransitionProvider>
					<Loader/>
					<AppRouterCacheProvider>
						{props.children}
					</AppRouterCacheProvider>
				</TransitionProvider>
			</body>
		</html>
	);
};


// using provider will probably not affect the rendering of the components, only the children will still be rendered on the server, but the component that read the context (usexxx hook) will be rendered on the client.

// configure documnet file?
// https://nextjs.org/docs/getting-started/installation#the-pages-directory-optional
// https://mui.com/material-ui/guides/nextjs/#typescript